### ISSUE TITLE
Undefined variable in dev environment

### ISSUE THREAD

**Issue by loicrey** [phpsword/sword-bundle#13]
Hi. On a fresh Docker one-liner installation, I have an error that is thrown by Symfony when visiting some of Wordpress admin pages

- https://sword.localhost/wp-admin/profile.php?wp_http_referer=%2Fwp-admin%2Fusers.php%3Fid%3D2
- https://sword.localhost/wp-admin/site-health.php

```
ErrorException:
Warning: Undefined variable $action

  at wp/core/wp-admin/site-health.php:58
  at require_once('/var/www/html/wp/core/wp-admin/site-health.php')
     (vendor/phpsword/sword-bundle/src/Loader/WordpressLoader.php:86)
  at Sword\SwordBundle\Loader\WordpressLoader->createWordpressResponse()
     (vendor/phpsword/sword-bundle/src/Controller/WordpressController.php:17)
  at Sword\SwordBundle\Controller\WordpressController->index()
     (vendor/symfony/http-kernel/HttpKernel.php:163)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw()
     (vendor/symfony/http-kernel/HttpKernel.php:74)
  at Symfony\Component\HttpKernel\HttpKernel->handle()
     (vendor/symfony/http-kernel/Kernel.php:184)
  at Symfony\Component\HttpKernel\Kernel->handle()
     (vendor/symfony/runtime/Runner/Symfony/HttpKernelRunner.php:35)
  at Symfony\Component\Runtime\Runner\Symfony\HttpKernelRunner->run()
     (vendor/autoload_runtime.php:29)
  at require_once('/var/www/html/vendor/autoload_runtime.php')
     (public/index.php:5)         
```       

In the wp core, it seems that this variable is not always defined
<img width="600" alt="image" src="https://user-images.githubusercontent.com/19840227/230999472-61efba25-364d-41ae-936c-56829327d564.png">

If I change my `APP_ENV` env variable to `prod` instead of `dev`, page loads fine.

**Comment by williarin** [comment]
The fix is to add this line at the end at `wp-config.php` right after requring `wp-settings.php`:

```php
global $action;
```

It's being unset in `wp-includes/default-filters.php`.
I'll fix it for new installs but for now only manual fix is possible for existing installs.

**Comment by loicrey** [comment]
Fixed for me, thanks for the quick reply and fix !
