### ISSUE TITLE
Rebase or merge? Opinions needed

### ISSUE THREAD

**Issue by williarin** [phpsword/sword-bundle#16]
What's the best option for PRs, rebase or merge?
I've only worked with rebase so far as mostly the sole contributor but it seems that it creates co-authored commits when a contributor makes a PR, which is odd.

Any opinion on what is the cleaner for open-source projects?

**Comment by loicrey** [comment]
I personally prefer using rebase to update working branch with staging or master, and using merge to retrieve work from someone else, or when approving and merging pull request to common branches like staging.

We also do this where I work (+50 developers)

**Comment by williarin** [comment]
Thanks, it seems indeed to be the best option.
