### ISSUE TITLE
Can't connect to the database :(

### ISSUE THREAD

**Issue by sanchobor** [phpsword/sword-bundle#20]
Hi, guys, 

I'm getting this: "error establishing a database connection" and can't debug it and connect the DB with the .env file. Is there something basic I'm missing? I'm not very familiar with docker and Symfony 6, I'm working with Symfony 4 mostly. 

Regards, 
Boris

**Comment by williarin** [comment]
Hi, does this happen right after installation? If that's the case it's probably because the MySQL container is not ready yet.
If it happens regardless of the timing, check if all containers are running in Docker Desktop (they should be green and not gray or red). Also check the logs of the MySQL container by clicking on it, and see if there's an error.

**Comment by aroberts91** [comment]
I'm also having this issue. Appears the mysql container is failing to initialise due to the following error:

```
mysql_1    | 2024-05-02T14:59:48.142891Z 0 [ERROR] [MY-000067] [Server] unknown variable 'default-authentication-plugin=mysql_native_password'.
mysql_1    | 2024-05-02T14:59:48.143475Z 0 [ERROR] [MY-010119] [Server] Aborting
```

**Comment by williarin** [comment]
Indeed the compose files are outdated. This line should be removed.
Also as MySQL is not semver, 8.1~8.4 are [innovation releases](https://dev.mysql.com/blog-archive/introducing-mysql-innovation-and-long-term-support-lts-versions/) and the compose image should be `mysql:8.0` or `mysql:8.0.37` for production use.

I'll make a fix soon but that will only apply to later installs unfortunately.

For existing installs, a [manual upgrade](https://www.digitalocean.com/community/questions/how-to-change-caching_sha2_password-to-mysql_native_password-on-a-digitalocean-s-managed-mysql-database) of the password is necessary for production databases, or recreate it completely as you mentioned.

**Comment by williarin** [comment]
It's fixed with the latest installer. I've restricted MySQL to 8.0.37 and removed mysql_native_password.
