### ISSUE TITLE
Question: Create entity 

### ISSUE THREAD

**Issue by Romaixn** [phpsword/sword-bundle#4]
Hello ! Is it possible to create entities on the Symfony side and then use them in WordPress?

Thank you for your answer and for this very useful tool!

**Comment by williarin** [comment]
Yes it's possible. I just released [1.0.0](https://github.com/phpsword/sword-bundle/releases/tag/1.0.0) version which fixes a `make:migration` problem.

Once you've created your entity, you can either inject your repositories in your `WordpressService` classes, or use `\Sword\SwordBundle\Helper\get_symfony_service` in your template to grab a public service.

Take a look [here](https://getsword.com/guide/tutorial/widgets.html#dependency-injection) to see an example on how to create a public service. But in most cases you should be able to use a `WordpressService` class with standard Symfony DI.

**Comment by Romaixn** [comment]
Awesome, thanks for this new version ! 🚀
