### ISSUE TITLE
404 editing a post

### ISSUE THREAD

**Issue by lucaspouchot** [phpsword/sword-bundle#8]
Hi,
On a from scratch installation, I cannot update a Wordpress post, I got 404.

![image](https://user-images.githubusercontent.com/55501335/208654758-7b203782-0276-4809-89f3-b017db91cdf6.png)

**Comment by williarin** [comment]
Indeed I can reproduced the problem, thank you for finding this issue. The problem goes away if you change the permalink structure in Settings/Permalinks.

I believe it's an nginx configuration issue, I'll look into it.

**Comment by williarin** [comment]
To fix this, remove the `internal` line in nginx config in `./docker/nginx/conf.d/default.conf` and rebuild your nginx container.

https://github.com/phpsword/sword-bundle/blob/ea77394665ba973efafc5e33b9eb97aec1abe1cf/install/docker/nginx/conf.d/default.conf#L27

I'll make a PR soon but that will only impact new projects.
